### ISSUE TITLE
解析报错！！！

### ISSUE THREAD

**Issue by momtboy** [F-loat/mpvue-wxParse#63]
传入的富文本内容为：
`“&lt;ol&gt;&lt;li&gt;&lt;img src=&quot;http://39.108.165.241/testImages/skuRemark/2019/01/13/8dd0175f-7304-4e35-b73c-ba95955b6a6f.png&quot; style=&quot;max-width:30%;&quot;&gt;&lt;/li&gt;&lt;li&gt;&lt;br&gt;&lt;/li&gt;&lt;li&gt;今天天气不错。&lt;/li&gt;&lt;/ol&gt;&lt;p&gt;&lt;br&gt;&lt;/p&gt;”`

报错内容为：

thirdScriptError
html.replace is not a function;at pages/mealDetail/main page lifeCycleMethod onReady function
TypeError: html.replace is not a function
    at trimHtml (http://127.0.0.1:38538/appservice/common/vendor.js:10562:17)
    at html2json (http://127.0.0.1:38538/appservice/common/vendor.js:10579:12)
    at VueComponent.nodes (http://127.0.0.1:38538/appservice/pages/mealDetail/main.js:624:95)
    at Watcher.get (http://127.0.0.1:38538/appservice/common/vendor.js:2407:31)
    at Watcher.evaluate (http://127.0.0.1:38538/appservice/common/vendor.js:2511:27)
    at VueComponent.computedGetter [as nodes] (http://127.0.0.1:38538/appservice/common/vendor.js:2732:23)
    at VueComponent.render (http://127.0.0.1:38538/appservice/pages/mealDetail/main.js:3960:18)
    at VueComponent.Vue._render (http://127.0.0.1:38538/appservice/common/vendor.js:3437:28)
    at VueComponent.updateComponent (http://127.0.0.1:38538/appservice/common/vendor.js:2101:27)
    at Watcher.get (http://127.0.0.1:38538/appservice/common/vendor.js:2407:31)

**Comment by F-loat** [comment]
未复现，可以用 examples 目录中的示例试下
